# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
