# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_Number', models.TextField()),
                ('Likes', models.TextField()),
                ('Followers', models.TextField()),
                ('Following', models.TextField()),
                ('User', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
    ]
