# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Followers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='Following',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='Image_Number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='Likes',
            field=models.IntegerField(),
        ),
    ]
