# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160403_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Image_Number',
        ),
    ]
