# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160403_0121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
