# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Likes', models.IntegerField()),
                ('User', models.TextField()),
                ('Posts', models.IntegerField(null=True)),
                ('Followers', models.IntegerField(null=True)),
                ('Following', models.IntegerField()),
                ('image_url', models.TextField()),
            ],
        ),
    ]
