# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tag',
            field=models.TextField(null=True),
        ),
    ]
