# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_image_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tag',
        ),
    ]
