# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_image_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Following',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='Likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='User',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
