# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20160404_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_link',
            field=models.TextField(null=True),
        ),
    ]
