# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_image_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_datatype',
            field=models.TextField(null=True),
        ),
    ]
