# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_image_image_datatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post_date',
            field=models.DateField(null=True),
        ),
    ]
